
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.coffeproject;

/**
 *
 * @author Administrator
 */
import javax.swing.*;  
import java.awt.event.*;
import java.io.File;
import javax.swing.JTextPane;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Menu extends javax.swing.JFrame{

   
    public Menu() {
        initComponents();
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_price = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TP = new javax.swing.JTextPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_Clear = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        tf_Total = new javax.swing.JTextField();
        Print = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CoffeeShop");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("TH Baijam", 0, 36)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 96, 110, 39);

        jLabel2.setText("Esspresso");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(28, 177, 60, 14);

        jLabel3.setText("Americano");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 218, 70, 14);

        jLabel4.setText("Latte");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(51, 259, 40, 14);

        jLabel5.setText("Cappuccino");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 300, 70, 14);

        jLabel6.setText("GreenTea");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(29, 341, 60, 14);

        jLabel7.setText("ThaiTea");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(37, 382, 60, 14);

        jLabel8.setText("Cocoa");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(37, 423, 60, 14);

        jCheckBox2.setText("35");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(94, 214, 37, 23);

        jCheckBox3.setText("35");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(94, 255, 37, 23);

        jCheckBox4.setText("35");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(94, 296, 37, 23);

        jCheckBox5.setText("20");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(94, 337, 37, 23);

        jCheckBox6.setText("20");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(94, 378, 37, 23);

        jCheckBox7.setText("20");
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(94, 419, 37, 23);

        jCheckBox8.setText("45");
        getContentPane().add(jCheckBox8);
        jCheckBox8.setBounds(131, 173, 37, 23);

        jCheckBox9.setText("45");
        getContentPane().add(jCheckBox9);
        jCheckBox9.setBounds(133, 214, 37, 23);

        jCheckBox10.setText("45");
        getContentPane().add(jCheckBox10);
        jCheckBox10.setBounds(133, 255, 37, 23);

        jCheckBox11.setText("45");
        getContentPane().add(jCheckBox11);
        jCheckBox11.setBounds(133, 296, 37, 23);

        jCheckBox12.setText("25");
        getContentPane().add(jCheckBox12);
        jCheckBox12.setBounds(133, 337, 37, 23);

        jCheckBox13.setText("25");
        getContentPane().add(jCheckBox13);
        jCheckBox13.setBounds(131, 378, 37, 23);

        jCheckBox14.setText("25");
        getContentPane().add(jCheckBox14);
        jCheckBox14.setBounds(131, 419, 37, 23);

        jCheckBox15.setText("50");
        getContentPane().add(jCheckBox15);
        jCheckBox15.setBounds(170, 173, 37, 23);

        jCheckBox16.setText("50");
        getContentPane().add(jCheckBox16);
        jCheckBox16.setBounds(172, 255, 37, 23);

        jCheckBox17.setText("50");
        getContentPane().add(jCheckBox17);
        jCheckBox17.setBounds(172, 296, 37, 23);

        jCheckBox18.setText("30");
        getContentPane().add(jCheckBox18);
        jCheckBox18.setBounds(172, 337, 37, 23);

        jCheckBox19.setText("30");
        getContentPane().add(jCheckBox19);
        jCheckBox19.setBounds(170, 378, 37, 23);

        jCheckBox20.setText("30");
        getContentPane().add(jCheckBox20);
        jCheckBox20.setBounds(170, 419, 37, 23);

        jLabel9.setText("Hot");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(94, 152, 40, 14);

        jLabel10.setText("Ice");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 152, 30, 14);

        jLabel11.setText("Frappe");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(173, 152, 50, 14);

        jLabel12.setText("Milk");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(254, 177, 90, 14);

        jLabel13.setText("MilkTea");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(254, 218, 120, 14);

        jLabel14.setText("LemonTea");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(254, 259, 120, 14);

        jLabel15.setText("Milo");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(254, 300, 120, 14);

        jLabel16.setText("NestCafe");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(254, 345, 120, 10);

        jLabel17.setText("NestcaTea");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(254, 382, 150, 14);

        jLabel18.setText("ItalianSoda (Cantaloupe,Strawberry,Apple,BlueHawai)");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(254, 423, 320, 14);

        jLabel19.setText("Red lime Soda");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(254, 464, 220, 14);

        jLabel20.setText("Honey lime Soda");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(254, 501, 190, 14);

        jCheckBox21.setText("20");
        getContentPane().add(jCheckBox21);
        jCheckBox21.setBounds(524, 173, 37, 23);

        jCheckBox22.setText("20");
        getContentPane().add(jCheckBox22);
        jCheckBox22.setBounds(524, 296, 37, 23);

        jCheckBox23.setText("20");
        getContentPane().add(jCheckBox23);
        jCheckBox23.setBounds(524, 337, 37, 23);

        jCheckBox24.setText("20");
        getContentPane().add(jCheckBox24);
        jCheckBox24.setBounds(524, 378, 37, 23);

        jCheckBox25.setText("25");
        getContentPane().add(jCheckBox25);
        jCheckBox25.setBounds(563, 173, 37, 23);

        jCheckBox26.setText("25");
        getContentPane().add(jCheckBox26);
        jCheckBox26.setBounds(563, 214, 37, 23);

        jCheckBox27.setText("25");
        getContentPane().add(jCheckBox27);
        jCheckBox27.setBounds(563, 255, 37, 23);

        jCheckBox28.setText("25");
        getContentPane().add(jCheckBox28);
        jCheckBox28.setBounds(563, 296, 37, 23);

        jCheckBox29.setText("25");
        getContentPane().add(jCheckBox29);
        jCheckBox29.setBounds(563, 337, 37, 23);

        jCheckBox30.setText("25");
        getContentPane().add(jCheckBox30);
        jCheckBox30.setBounds(563, 378, 37, 23);

        jCheckBox31.setText("25");
        getContentPane().add(jCheckBox31);
        jCheckBox31.setBounds(563, 460, 37, 23);

        jCheckBox32.setText("25");
        getContentPane().add(jCheckBox32);
        jCheckBox32.setBounds(563, 501, 37, 23);

        jCheckBox33.setText("30");
        getContentPane().add(jCheckBox33);
        jCheckBox33.setBounds(602, 173, 37, 23);

        jCheckBox34.setText("30");
        getContentPane().add(jCheckBox34);
        jCheckBox34.setBounds(602, 214, 37, 23);

        jCheckBox35.setText("30");
        getContentPane().add(jCheckBox35);
        jCheckBox35.setBounds(602, 255, 37, 23);

        jCheckBox36.setText("30");
        getContentPane().add(jCheckBox36);
        jCheckBox36.setBounds(602, 296, 37, 23);

        jCheckBox37.setText("30");
        getContentPane().add(jCheckBox37);
        jCheckBox37.setBounds(602, 337, 37, 23);

        jCheckBox38.setText("30");
        getContentPane().add(jCheckBox38);
        jCheckBox38.setBounds(602, 378, 37, 23);

        jCheckBox39.setText("25");
        getContentPane().add(jCheckBox39);
        jCheckBox39.setBounds(602, 425, 37, 23);

        jLabel21.setText("Hot");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(510, 150, 40, 14);

        jLabel22.setText("Ice");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(559, 152, 30, 14);

        jLabel23.setText("Frappe");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(605, 152, 60, 14);

        btn_price.setText("OK");
        btn_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_priceMouseClicked(evt);
            }
        });
        getContentPane().add(btn_price);
        btn_price.setBounds(703, 466, 85, 33);

        jLabel25.setFont(new java.awt.Font("Vijaya", 0, 48)); // NOI18N
        jLabel25.setText("CofeeShop");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(350, 20, 270, 50);

        jScrollPane2.setViewportView(TP);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(716, 138, 279, 261);

        jCheckBox1.setText("35");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(94, 173, 37, 23);

        btn_Clear.setText("Clear");
        btn_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ClearMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Clear);
        btn_Clear.setBounds(910, 467, 85, 31);

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel24.setText("Total");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(770, 420, 39, 23);

        tf_Total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_Total.setEnabled(false);
        getContentPane().add(tf_Total);
        tf_Total.setBounds(826, 419, 78, 28);

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        getContentPane().add(Print);
        Print.setBounds(825, 530, 85, 31);

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\Cup of Coffee Background -wallpapers.io-1281x854.jpg")); // NOI18N
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(0, 0, 1110, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void btn_priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_priceMouseClicked
        // TODO add your handling code here:
    Date date = new Date();
    float amount = 0;  
    String msg = ""; 
    msg+="****************************************************\n";
    msg+="--------------------CofeeShop-----------------------\n";
    msg+="****************************************************\n";
    if(jCheckBox1.isSelected() == true){  
        amount += 35;  
        msg += "Esspresso(Hot)                         35B\n";  
    }  
    if(jCheckBox8.isSelected() == true){  
        amount += 45;  
        msg += "Esspresso(Ice)                         45B\n";  
    }  
    if(jCheckBox15.isSelected() == true){  
        amount += 50;  
        msg += "Esspresso(Frappe)                      50B\n";  
    }    
    if(jCheckBox2.isSelected() == true){  
        amount += 35;  
        msg += "Americano(Hot)                         35B\n";
    }    
    if(jCheckBox9.isSelected() == true){  
        amount += 45;  
        msg += "Americano(Ice)                         45B\n";
    }    
    if(jCheckBox3.isSelected() == true){  
        amount += 30;  
        msg += "Latte(Hot)                             35B\n";
    }
    if(jCheckBox10.isSelected() == true){  
        amount += 45;  
        msg += "Latte(Ice)                             45B\n";   
    }
    if(jCheckBox16.isSelected() == true){  
        amount += 50;  
        msg += "Latte(Frappe)                          50B\n";    
    }
    if(jCheckBox4.isSelected() == true){  
        amount = amount+35;  
        msg += "Cappuccino(Hot)                        35B\n";   
    }
    if(jCheckBox11.isSelected() == true){  
        amount += 45;  
        msg += "Cappuccino(Ice)                        45B\n";
    }
    if(jCheckBox17.isSelected() == true){  
        amount += 50;  
        msg += "Cappuccino(Frappe)                     50B\n";
    }
    if(jCheckBox5.isSelected() == true){  
        amount += 20;  
        msg += "GreenTea(Hot)                          20B\n";
    }
    if(jCheckBox12.isSelected() == true){  
        amount += 25;  
        msg += "GreenTea(Ice)                          25B\n";
    }
    if(jCheckBox18.isSelected() == true){  
        amount += 30;  
        msg += "GreenTea(Frappe)                       30B\n";
    }
    if(jCheckBox6.isSelected() == true){  
        amount += 20;  
        msg += "ThaiTea(Hot)                           20B\n";
    }
    if(jCheckBox13.isSelected() == true){  
        amount += 25;  
        msg += "ThaiTea(Ice)                           25B\n";
    }
    if(jCheckBox19.isSelected() == true){  
        amount += 30;  
        msg += "ThaiTea(Frappe)                        30B\n";
    }
    if(jCheckBox7.isSelected() == true){  
        amount += 20;  
        msg += "Cocoa(Hot)                             20B\n";
    }
    if(jCheckBox14.isSelected() == true){  
        amount += 25;  
        msg += "Cocoa(Ice)                             25B\n";
    }
    if(jCheckBox20.isSelected() == true){  
        amount += 30;  
        msg += "Cocoa(Frappe)                          300B\n";
    }
    if(jCheckBox21.isSelected() == true){  
        amount += 20;  
        msg += "Milk(Hot)                              20B\n";
    }
    if(jCheckBox25.isSelected() == true){  
        amount += 25;  
        msg += "Milk(Ice)                              25B\n";
    }
    if(jCheckBox33.isSelected() == true){  
        amount += 30;  
        msg += "Milk(Frappe)                           30B\n";
    }
    if(jCheckBox26.isSelected() == true){  
        amount += 25;  
        msg += "MilkTea(Ice)                           25B\n";
    }
    if(jCheckBox34.isSelected() == true){  
        amount += 30;  
        msg += "MilkTea(Frappe)                        30B\n";
    }
    if(jCheckBox27.isSelected() == true){  
        amount += 20;  
        msg += "LemonTea(Ice)                          25B\n";
    }
    if(jCheckBox35.isSelected() == true){  
        amount += 25;  
        msg += "LemonTea(Frappe)                       30B\n";
    }
    if(jCheckBox21.isSelected() == true){  
        amount += 20;  
        msg += "Milo(Hot)                              20B\n";
    }
    if(jCheckBox28.isSelected() == true){  
        amount += 25;  
        msg += "Milo(Ice)                              25B\n";
    }
    if(jCheckBox36.isSelected() == true){  
        amount += 30;  
        msg += "Milo(Frappe)                           30B\n";
    }
    if(jCheckBox22.isSelected() == true){  
        amount += 20;  
        msg += "NestCafe(Hot)                          20B\n";
    }
    if(jCheckBox29.isSelected() == true){  
        amount += 25;  
        msg += "NestCafe(Ice)                          25B\n";
    }
    if(jCheckBox37.isSelected() == true){  
        amount += 30;  
        msg += "NestCafe(Frappe)                       30B\n";
    }
    if(jCheckBox23.isSelected() == true){  
        amount += 20;  
        msg += "NestcaTea(Hot)                         20B\n";
    }
    if(jCheckBox30.isSelected() == true){  
        amount += 25;  
        msg += "NestcaTea(Ice)                         25B\n";
    }
    if(jCheckBox38.isSelected() == true){  
        amount += 30;  
        msg += "NestcaTea(Frappe)                      30B\n";
    }
    if(jCheckBox39.isSelected() == true){  
        amount += 25;  
        msg += "ItalianSoda (Cantaloupe,"
             + "Strawberry,Apple,BlueHawai)(Frappe)   25\n";            
    }
    if(jCheckBox31.isSelected() == true){  
        amount += 25;  
        msg += "Red lime Soda(Ice)                     25B\n";
    }
    if(jCheckBox32.isSelected() == true){  
        amount += 25;  
        msg += "Honey lime Soda(Ice)                   25B\n";
    }
    
    msg+="-----------------------------------------------------------------\n";  
       
    TP.setText( msg);
    TP.setText( msg + date.toString()+"\t\n"+"\n\tTotal: "+ amount +"\t\n"+"\n\nC:\\Users\\Administrator\\Documents\\Payment.txt"); 
    tf_Total.setText(String.valueOf(amount + "B"));


           
    }//GEN-LAST:event_btn_priceMouseClicked
   
     
        
    
    
    private void btn_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClearMouseClicked
        // TODO add your handling code here:
    TP.setText("");
    tf_Total.setText(""); 
    jCheckBox1.setSelected(false);
    jCheckBox2.setSelected(false);
    jCheckBox3.setSelected(false);
    jCheckBox4.setSelected(false);
    jCheckBox5.setSelected(false);
    jCheckBox6.setSelected(false);
    jCheckBox7.setSelected(false);
    jCheckBox8.setSelected(false);
    jCheckBox9.setSelected(false);
    jCheckBox10.setSelected(false);
    jCheckBox11.setSelected(false);
    jCheckBox12.setSelected(false);
    jCheckBox13.setSelected(false);
    jCheckBox14.setSelected(false);
    jCheckBox15.setSelected(false);
    jCheckBox16.setSelected(false);
    jCheckBox17.setSelected(false);
    jCheckBox18.setSelected(false);
    jCheckBox19.setSelected(false);
    jCheckBox20.setSelected(false);
    jCheckBox21.setSelected(false);
    jCheckBox22.setSelected(false);
    jCheckBox23.setSelected(false);
    jCheckBox24.setSelected(false);
    jCheckBox25.setSelected(false);
    jCheckBox26.setSelected(false);
    jCheckBox27.setSelected(false);
    jCheckBox28.setSelected(false);
    jCheckBox29.setSelected(false);
    jCheckBox30.setSelected(false);
    jCheckBox31.setSelected(false);
    jCheckBox32.setSelected(false);
    jCheckBox33.setSelected(false);
    jCheckBox34.setSelected(false);
    jCheckBox35.setSelected(false);
    jCheckBox36.setSelected(false);
    jCheckBox37.setSelected(false);
    jCheckBox38.setSelected(false);
    jCheckBox39.setSelected(false);
    

    

    
    
    
    
    
    
    }//GEN-LAST:event_btn_ClearMouseClicked

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
    String filePath = "C:\\Users\\Administrator\\Documents\\Payment.txt";
    File file = new File(filePath);
    FileWriter writer;
    try {
        writer = new FileWriter(file,true);
        writer.write(TP.getText());
        writer.close();
        
        System.out.println("Write success");
       
        }catch (IOException e) {
            e.printStackTrace();
        }
      
     
         
    
     
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JTextPane TP;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_price;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tf_Total;
    // End of variables declaration//GEN-END:variables
}
